export const CATEGORIES_ACTION_TYPES = {
  // SET_CATEGORIES: 'category/SET_CATEGORIES',
  FETCH_CATEGORIES_START: 'category/FETCH_CATEGORIES_START', // when we begin our API request
  FETCH_CATEGORIES_SUCCESS: 'category/FETCH_CATEGORIES_SUCCESS', // SET_CATEGORIES will now be set when it succeeds
  FETCH_CATEGORIES_FAILURE: 'category/FETCH_CATEGORIES_FAILURE'
};
